var Helix_DB_SQL_ComparisonTrait =
[
    [ "is", "Helix_DB_SQL_ComparisonTrait.html#08df9ff", null ],
    [ "isBetween", "Helix_DB_SQL_ComparisonTrait.html#94d1c68", null ],
    [ "isEqual", "Helix_DB_SQL_ComparisonTrait.html#679d44f", null ],
    [ "isFalse", "Helix_DB_SQL_ComparisonTrait.html#18b7448", null ],
    [ "isGt", "Helix_DB_SQL_ComparisonTrait.html#1b5bec6", null ],
    [ "isGtAny", "Helix_DB_SQL_ComparisonTrait.html#f44a99f", null ],
    [ "isGte", "Helix_DB_SQL_ComparisonTrait.html#cd47989", null ],
    [ "isGteAny", "Helix_DB_SQL_ComparisonTrait.html#616d242", null ],
    [ "isLike", "Helix_DB_SQL_ComparisonTrait.html#3e80e92", null ],
    [ "isLt", "Helix_DB_SQL_ComparisonTrait.html#0b36d75", null ],
    [ "isLtAny", "Helix_DB_SQL_ComparisonTrait.html#74f8a76", null ],
    [ "isLte", "Helix_DB_SQL_ComparisonTrait.html#9f186e2", null ],
    [ "isLteAny", "Helix_DB_SQL_ComparisonTrait.html#9b680a5", null ],
    [ "isNot", "Helix_DB_SQL_ComparisonTrait.html#1520d9c", null ],
    [ "isNotBetween", "Helix_DB_SQL_ComparisonTrait.html#35c474b", null ],
    [ "isNotEqual", "Helix_DB_SQL_ComparisonTrait.html#7633756", null ],
    [ "isNotLike", "Helix_DB_SQL_ComparisonTrait.html#1d4b7f4", null ],
    [ "isNotNull", "Helix_DB_SQL_ComparisonTrait.html#9ffe042", null ],
    [ "isNotRegExp", "Helix_DB_SQL_ComparisonTrait.html#e1f9125", null ],
    [ "isNull", "Helix_DB_SQL_ComparisonTrait.html#8c2c02b", null ],
    [ "isRegExp", "Helix_DB_SQL_ComparisonTrait.html#ad13c5e", null ],
    [ "switch", "Helix_DB_SQL_ComparisonTrait.html#3272b9b", null ]
];