var Helix_DB_Fluent_DateTime_DateTimeTrait =
[
    [ "date", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#5767d7c", null ],
    [ "dateFormat", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#ed65890", null ],
    [ "datetime", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#869d755", null ],
    [ "day", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#3849cc5", null ],
    [ "dayOfWeek", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#139ce13", null ],
    [ "dayOfYear", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#e671fc0", null ],
    [ "diffDays", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#2f5414c", null ],
    [ "diffHours", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#196622f", null ],
    [ "diffMinutes", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#853ad6a", null ],
    [ "diffMonths", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#e6daa36", null ],
    [ "diffSeconds", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#883aa04", null ],
    [ "diffYears", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#6e26687", null ],
    [ "hours", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#6d6e301", null ],
    [ "iso8601", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#8650d90", null ],
    [ "julian", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#ea09a2c", null ],
    [ "minutes", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#e90d103", null ],
    [ "month", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#431211f", null ],
    [ "seconds", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#abc0db4", null ],
    [ "time", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#d78f8ba", null ],
    [ "timestamp", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#b2398f0", null ],
    [ "weekOfYear", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#feb7a44", null ],
    [ "year", "Helix_DB_Fluent_DateTime_DateTimeTrait.html#b50d156", null ]
];