var Helix_DB_Record =
[
    [ "$eav", "Helix_DB_Record.html#2177d2d", null ],
    [ "$proto", "Helix_DB_Record.html#2f0e87b", null ],
    [ "$serializer", "Helix_DB_Record.html#867a502", null ],
    [ "EAV_BATCH_LOAD", "Helix_DB_Record.html#1ce31ba", null ],
    [ "__construct", "Helix_DB_Record.html#75f99f5", null ],
    [ "factory", "Helix_DB_Record.html#4e03ac3", null ],
    [ "fetchAll", "Helix_DB_Record.html#c686b9a", null ],
    [ "fetchEach", "Helix_DB_Record.html#c5a765b", null ],
    [ "findAll", "Helix_DB_Record.html#42c0e36", null ],
    [ "findFirst", "Helix_DB_Record.html#dffc0a7", null ],
    [ "getClass", "Helix_DB_Record.html#0c03627", null ],
    [ "getEav", "Helix_DB_Record.html#fe476ed", null ],
    [ "getProto", "Helix_DB_Record.html#44b76d2", null ],
    [ "getSerializer", "Helix_DB_Record.html#5fff2df", null ],
    [ "load", "Helix_DB_Record.html#2732fe6", null ],
    [ "loadAll", "Helix_DB_Record.html#fde4b24", null ],
    [ "loadEav", "Helix_DB_Record.html#1e28fdf", null ],
    [ "save", "Helix_DB_Record.html#12fd03a", null ],
    [ "saveEav", "Helix_DB_Record.html#3ac3c3a", null ],
    [ "saveInsert", "Helix_DB_Record.html#27a4abf", null ],
    [ "saveUpdate", "Helix_DB_Record.html#b6d0850", null ],
    [ "setProto", "Helix_DB_Record.html#6702635", null ]
];