var Helix_DB_Reflection =
[
    [ "$class", "Helix_DB_Reflection.html#692b74c", null ],
    [ "$columns", "Helix_DB_Reflection.html#47ff24c", null ],
    [ "$db", "Helix_DB_Reflection.html#d144aa2", null ],
    [ "$defaults", "Helix_DB_Reflection.html#719011a", null ],
    [ "$properties", "Helix_DB_Reflection.html#bb24f1b", null ],
    [ "$unique", "Helix_DB_Reflection.html#3c7811a", null ],
    [ "RX_EAV", "Helix_DB_Reflection.html#e04da41", null ],
    [ "RX_EAV_VAR", "Helix_DB_Reflection.html#0ff0f46", null ],
    [ "RX_FOREIGN", "Helix_DB_Reflection.html#f951594", null ],
    [ "RX_IS_COLUMN", "Helix_DB_Reflection.html#97c9e23", null ],
    [ "RX_JUNCTION", "Helix_DB_Reflection.html#16d3814", null ],
    [ "RX_NULL", "Helix_DB_Reflection.html#0634e04", null ],
    [ "RX_RECORD", "Helix_DB_Reflection.html#7a5bbc2", null ],
    [ "RX_UNIQUE", "Helix_DB_Reflection.html#c79905c", null ],
    [ "RX_VAR", "Helix_DB_Reflection.html#31d81cd", null ],
    [ "SCALARS", "Helix_DB_Reflection.html#b2dc14c", null ],
    [ "__construct", "Helix_DB_Reflection.html#75f99f5", null ],
    [ "factory", "Helix_DB_Reflection.html#eb81a04", null ],
    [ "getColumns", "Helix_DB_Reflection.html#dc14720", null ],
    [ "getEav", "Helix_DB_Reflection.html#fe476ed", null ],
    [ "getForeignClasses", "Helix_DB_Reflection.html#331d04b", null ],
    [ "getJunctionTable", "Helix_DB_Reflection.html#afa70de", null ],
    [ "getRecordTable", "Helix_DB_Reflection.html#998836f", null ],
    [ "getType", "Helix_DB_Reflection.html#767a2f1", null ],
    [ "getType_reflection", "Helix_DB_Reflection.html#e1d7f1e", null ],
    [ "getType_var", "Helix_DB_Reflection.html#2bf4f1c", null ],
    [ "getUnique", "Helix_DB_Reflection.html#eb3b7aa", null ],
    [ "getUniqueGroup", "Helix_DB_Reflection.html#fc9f7ff", null ],
    [ "getValue", "Helix_DB_Reflection.html#5d0fb89", null ],
    [ "isNullable", "Helix_DB_Reflection.html#30e2220", null ],
    [ "isUnique", "Helix_DB_Reflection.html#4b391d5", null ],
    [ "newProto", "Helix_DB_Reflection.html#cfb8a4b", null ],
    [ "setValue", "Helix_DB_Reflection.html#602705c", null ]
];