var Helix_DB_Record =
[
    [ "$eav", "Helix_DB_Record.html#2177d2d", null ],
    [ "$nullable", "Helix_DB_Record.html#027c7e1", null ],
    [ "$properties", "Helix_DB_Record.html#bb24f1b", null ],
    [ "$proto", "Helix_DB_Record.html#2f0e87b", null ],
    [ "$types", "Helix_DB_Record.html#f594f1e", null ],
    [ "__construct", "Helix_DB_Record.html#8b4dd5b", null ],
    [ "factory", "Helix_DB_Record.html#6e94e70", null ],
    [ "find", "Helix_DB_Record.html#cfb2422", null ],
    [ "fromClass", "Helix_DB_Record.html#af3c67b", null ],
    [ "getAll", "Helix_DB_Record.html#93f5255", null ],
    [ "getClass", "Helix_DB_Record.html#0c03627", null ],
    [ "getEach", "Helix_DB_Record.html#af970d8", null ],
    [ "getEav", "Helix_DB_Record.html#dd36252", null ],
    [ "getProperties", "Helix_DB_Record.html#ff95e70", null ],
    [ "getProto", "Helix_DB_Record.html#44b76d2", null ],
    [ "getTypes", "Helix_DB_Record.html#0324f76", null ],
    [ "getValues", "Helix_DB_Record.html#aaef9e8", null ],
    [ "isNullable", "Helix_DB_Record.html#30e2220", null ],
    [ "load", "Helix_DB_Record.html#790b332", null ],
    [ "loadAll", "Helix_DB_Record.html#fde4b24", null ],
    [ "loadEav", "Helix_DB_Record.html#1e28fdf", null ],
    [ "save", "Helix_DB_Record.html#12fd03a", null ],
    [ "saveEav", "Helix_DB_Record.html#3ac3c3a", null ],
    [ "saveInsert", "Helix_DB_Record.html#27a4abf", null ],
    [ "saveUpdate", "Helix_DB_Record.html#b6d0850", null ],
    [ "setProto", "Helix_DB_Record.html#6702635", null ],
    [ "setValues", "Helix_DB_Record.html#3a3a37d", null ]
];