var Helix_DB =
[
    [ "$junctions", "Helix_DB.html#86c2f9f", null ],
    [ "$logger", "Helix_DB.html#ce2b5bb", null ],
    [ "$records", "Helix_DB.html#6544e33", null ],
    [ "$tables", "Helix_DB.html#9afb92c", null ],
    [ "__construct", "Helix_DB.html#969db10", null ],
    [ "__toString", "Helix_DB.html#f5ddf7f", null ],
    [ "exec", "Helix_DB.html#660402d", null ],
    [ "factory", "Helix_DB.html#5c91022", null ],
    [ "getDriver", "Helix_DB.html#480bdda", null ],
    [ "getJunction", "Helix_DB.html#0e422d4", null ],
    [ "getLogger", "Helix_DB.html#88507d6", null ],
    [ "getRecord", "Helix_DB.html#e17b2d0", null ],
    [ "getTable", "Helix_DB.html#07ddcca", null ],
    [ "isMySQL", "Helix_DB.html#f7f4ed4", null ],
    [ "isPostgreSQL", "Helix_DB.html#6bbfe51", null ],
    [ "isSQLite", "Helix_DB.html#8b842bf", null ],
    [ "match", "Helix_DB.html#ce43e84", null ],
    [ "offsetExists", "Helix_DB.html#0fdaee3", null ],
    [ "offsetGet", "Helix_DB.html#62ef696", null ],
    [ "offsetSet", "Helix_DB.html#e46b7a3", null ],
    [ "offsetUnset", "Helix_DB.html#fd4b563", null ],
    [ "prepare", "Helix_DB.html#187ddf1", null ],
    [ "query", "Helix_DB.html#e9fa9e2", null ],
    [ "quote", "Helix_DB.html#38a3ff8", null ],
    [ "quoteArray", "Helix_DB.html#a5b531f", null ],
    [ "quoteList", "Helix_DB.html#edb7cb0", null ],
    [ "save", "Helix_DB.html#12fd03a", null ],
    [ "setJunction", "Helix_DB.html#df401f1", null ],
    [ "setLogger", "Helix_DB.html#82c52bf", null ],
    [ "setRecord", "Helix_DB.html#c2d5b68", null ]
];