var Helix_DB_Record =
[
    [ "$eav", "Helix_DB_Record.html#2177d2d", null ],
    [ "$properties", "Helix_DB_Record.html#bb24f1b", null ],
    [ "$proto", "Helix_DB_Record.html#2f0e87b", null ],
    [ "$types", "Helix_DB_Record.html#8d85209", null ],
    [ "__construct", "Helix_DB_Record.html#8b4dd5b", null ],
    [ "factory", "Helix_DB_Record.html#6e94e70", null ],
    [ "find", "Helix_DB_Record.html#70b1b3c", null ],
    [ "fromClass", "Helix_DB_Record.html#af3c67b", null ],
    [ "getAll", "Helix_DB_Record.html#93f5255", null ],
    [ "getEach", "Helix_DB_Record.html#af970d8", null ],
    [ "getEav", "Helix_DB_Record.html#dd36252", null ],
    [ "getProto", "Helix_DB_Record.html#44b76d2", null ],
    [ "getValues", "Helix_DB_Record.html#aaef9e8", null ],
    [ "load", "Helix_DB_Record.html#790b332", null ],
    [ "loadEav", "Helix_DB_Record.html#1e28fdf", null ],
    [ "save", "Helix_DB_Record.html#12fd03a", null ],
    [ "saveEav", "Helix_DB_Record.html#3ac3c3a", null ],
    [ "saveInsert", "Helix_DB_Record.html#27a4abf", null ],
    [ "saveUpdate", "Helix_DB_Record.html#b6d0850", null ],
    [ "select", "Helix_DB_Record.html#3a608dd", null ],
    [ "setProto", "Helix_DB_Record.html#6702635", null ],
    [ "setValues", "Helix_DB_Record.html#3a3a37d", null ]
];