var Helix_Asana_Portfolio =
[
    [ "DIR", "Helix_Asana_Portfolio.html#382fec3", null ],
    [ "GRAPH", "Helix_Asana_Portfolio.html#0b028b2", null ],
    [ "MAP", "Helix_Asana_Portfolio.html#9c07f6e", null ],
    [ "TYPE", "Helix_Asana_Portfolio.html#490da94", null ],
    [ "_getParentNode", "Helix_Asana_Portfolio.html#cfbad12", null ],
    [ "addItem", "Helix_Asana_Portfolio.html#8e6fa5a", null ],
    [ "addItems", "Helix_Asana_Portfolio.html#9e916d0", null ],
    [ "getColor", "Helix_Asana_Portfolio.html#6cc27b1", null ],
    [ "getCreatedAt", "Helix_Asana_Portfolio.html#1adffdc", null ],
    [ "getCreatedBy", "Helix_Asana_Portfolio.html#c21942a", null ],
    [ "getItems", "Helix_Asana_Portfolio.html#e0a8fea", null ],
    [ "getIterator", "Helix_Asana_Portfolio.html#18a0647", null ],
    [ "getName", "Helix_Asana_Portfolio.html#8a0b8ec", null ],
    [ "getOwner", "Helix_Asana_Portfolio.html#4b54e5b", null ],
    [ "getProjects", "Helix_Asana_Portfolio.html#1ab990a", null ],
    [ "getWorkspace", "Helix_Asana_Portfolio.html#e076a3c", null ],
    [ "selectItems", "Helix_Asana_Portfolio.html#61012d3", null ],
    [ "setColor", "Helix_Asana_Portfolio.html#aecdf31", null ],
    [ "setMembers", "Helix_Asana_Portfolio.html#4ccdee9", null ],
    [ "setName", "Helix_Asana_Portfolio.html#2f41205", null ],
    [ "setOwner", "Helix_Asana_Portfolio.html#9c44cbc", null ],
    [ "setWorkspace", "Helix_Asana_Portfolio.html#cb9be28", null ]
];