var Helix_Asana_Task_Story =
[
    [ "DIR", "Helix_Asana_Task_Story.html#c482d92", null ],
    [ "MAP", "Helix_Asana_Task_Story.html#9c07f6e", null ],
    [ "TYPE", "Helix_Asana_Task_Story.html#0cb7892", null ],
    [ "TYPE_ASSIGNED", "Helix_Asana_Task_Story.html#9e8dfe1", null ],
    [ "TYPE_COMMENT_ADDED", "Helix_Asana_Task_Story.html#95cbd8a", null ],
    [ "TYPE_COMMENT_LIKED", "Helix_Asana_Task_Story.html#d554bba", null ],
    [ "TYPE_DUE_DATE_CHANGED", "Helix_Asana_Task_Story.html#a7e5e80", null ],
    [ "TYPE_LIKED", "Helix_Asana_Task_Story.html#5d9a4b3", null ],
    [ "TYPE_TAGGED", "Helix_Asana_Task_Story.html#39bed3e", null ],
    [ "_setData", "Helix_Asana_Task_Story.html#e470999", null ],
    [ "getCreatedAt", "Helix_Asana_Task_Story.html#1adffdc", null ],
    [ "getCreatedBy", "Helix_Asana_Task_Story.html#62f10f6", null ],
    [ "getLikes", "Helix_Asana_Task_Story.html#22343d9", null ],
    [ "getNumLikes", "Helix_Asana_Task_Story.html#d4019e6", null ],
    [ "getParentNode", "Helix_Asana_Task_Story.html#778f410", null ],
    [ "getResourceSubtype", "Helix_Asana_Task_Story.html#4a1ee7c", null ],
    [ "getSource", "Helix_Asana_Task_Story.html#fb2ed40", null ],
    [ "getTarget", "Helix_Asana_Task_Story.html#b5024d5", null ],
    [ "getText", "Helix_Asana_Task_Story.html#6da0a6f", null ],
    [ "isAssignment", "Helix_Asana_Task_Story.html#bd2b078", null ],
    [ "isComment", "Helix_Asana_Task_Story.html#a9dd6c7", null ],
    [ "isDueDate", "Helix_Asana_Task_Story.html#68f194c", null ],
    [ "isEdited", "Helix_Asana_Task_Story.html#8a05660", null ],
    [ "isFromApi", "Helix_Asana_Task_Story.html#bd48760", null ],
    [ "isFromWeb", "Helix_Asana_Task_Story.html#9e6bac9", null ],
    [ "isLiked", "Helix_Asana_Task_Story.html#8aa5bc7", null ],
    [ "isLikedComment", "Helix_Asana_Task_Story.html#b525adc", null ],
    [ "isLikedTask", "Helix_Asana_Task_Story.html#2194468", null ],
    [ "isPinned", "Helix_Asana_Task_Story.html#971a000", null ],
    [ "isTag", "Helix_Asana_Task_Story.html#0483633", null ],
    [ "selectLikes", "Helix_Asana_Task_Story.html#099aafb", null ],
    [ "setLiked", "Helix_Asana_Task_Story.html#1fedff5", null ],
    [ "setPinned", "Helix_Asana_Task_Story.html#669d945", null ],
    [ "setText", "Helix_Asana_Task_Story.html#2855bca", null ]
];