var Helix_Asana_User =
[
    [ "DIR", "Helix_Asana_User.html#c482d92", null ],
    [ "MAP", "Helix_Asana_User.html#9c07f6e", null ],
    [ "TYPE", "Helix_Asana_User.html#0cb7892", null ],
    [ "addToWorkspace", "Helix_Asana_User.html#75534b6", null ],
    [ "getDefaultWorkspace", "Helix_Asana_User.html#259bc92", null ],
    [ "getEmail", "Helix_Asana_User.html#30d49cf", null ],
    [ "getFavoritePortfolios", "Helix_Asana_User.html#8e11c7f", null ],
    [ "getFavoriteProjects", "Helix_Asana_User.html#d628b32", null ],
    [ "getFavorites", "Helix_Asana_User.html#43611ac", null ],
    [ "getFavoriteTags", "Helix_Asana_User.html#ea17bd7", null ],
    [ "getFavoriteTeams", "Helix_Asana_User.html#5a22dcc", null ],
    [ "getFavoriteUsers", "Helix_Asana_User.html#d4a4587", null ],
    [ "getName", "Helix_Asana_User.html#8a0b8ec", null ],
    [ "getPhoto", "Helix_Asana_User.html#b329969", null ],
    [ "getPoolKeys", "Helix_Asana_User.html#54bdc3f", null ],
    [ "getPortfolios", "Helix_Asana_User.html#4bb8fc6", null ],
    [ "getTaskList", "Helix_Asana_User.html#696e1eb", null ],
    [ "getTasks", "Helix_Asana_User.html#1c8abf1", null ],
    [ "getTeams", "Helix_Asana_User.html#2836239", null ],
    [ "getUrl", "Helix_Asana_User.html#277241c", null ],
    [ "getWorkspaces", "Helix_Asana_User.html#b094edd", null ],
    [ "removeFromWorkspace", "Helix_Asana_User.html#2a5db4d", null ]
];