var Helix_Asana_Portfolio =
[
    [ "DIR", "Helix_Asana_Portfolio.html#c482d92", null ],
    [ "MAP", "Helix_Asana_Portfolio.html#9c07f6e", null ],
    [ "TYPE", "Helix_Asana_Portfolio.html#0cb7892", null ],
    [ "addMember", "Helix_Asana_Portfolio.html#67f2efb", null ],
    [ "addMembers", "Helix_Asana_Portfolio.html#a176d75", null ],
    [ "addProject", "Helix_Asana_Portfolio.html#2062a44", null ],
    [ "getColor", "Helix_Asana_Portfolio.html#6cc27b1", null ],
    [ "getCreatedAt", "Helix_Asana_Portfolio.html#1adffdc", null ],
    [ "getCreatedBy", "Helix_Asana_Portfolio.html#c21942a", null ],
    [ "getIterator", "Helix_Asana_Portfolio.html#0a46d85", null ],
    [ "getMembers", "Helix_Asana_Portfolio.html#dad693b", null ],
    [ "getName", "Helix_Asana_Portfolio.html#8a0b8ec", null ],
    [ "getOwner", "Helix_Asana_Portfolio.html#4b54e5b", null ],
    [ "getParentNode", "Helix_Asana_Portfolio.html#4344576", null ],
    [ "getProjects", "Helix_Asana_Portfolio.html#1ab990a", null ],
    [ "getWorkspace", "Helix_Asana_Portfolio.html#e076a3c", null ],
    [ "hasMembers", "Helix_Asana_Portfolio.html#29f23fa", null ],
    [ "removeMember", "Helix_Asana_Portfolio.html#0a24b77", null ],
    [ "removeMembers", "Helix_Asana_Portfolio.html#e68ced1", null ],
    [ "removeProject", "Helix_Asana_Portfolio.html#17cbcc1", null ],
    [ "selectMembers", "Helix_Asana_Portfolio.html#a1bf0ba", null ],
    [ "selectProjects", "Helix_Asana_Portfolio.html#83d8530", null ],
    [ "setColor", "Helix_Asana_Portfolio.html#aecdf31", null ],
    [ "setMembers", "Helix_Asana_Portfolio.html#4ccdee9", null ],
    [ "setName", "Helix_Asana_Portfolio.html#2f41205", null ],
    [ "setOwner", "Helix_Asana_Portfolio.html#9c44cbc", null ],
    [ "setWorkspace", "Helix_Asana_Portfolio.html#cb9be28", null ]
];