var Helix_Asana_Workspace =
[
    [ "DIR", "Helix_Asana_Workspace.html#c482d92", null ],
    [ "TYPE", "Helix_Asana_Workspace.html#0cb7892", null ],
    [ "export", "Helix_Asana_Workspace.html#e7e84c5", null ],
    [ "find", "Helix_Asana_Workspace.html#d019e0f", null ],
    [ "findCustomFields", "Helix_Asana_Workspace.html#0e2faa3", null ],
    [ "findPortfolios", "Helix_Asana_Workspace.html#98459bd", null ],
    [ "findProjects", "Helix_Asana_Workspace.html#cb79578", null ],
    [ "findTags", "Helix_Asana_Workspace.html#126734c", null ],
    [ "findTasks", "Helix_Asana_Workspace.html#d3af38b", null ],
    [ "getCustomFields", "Helix_Asana_Workspace.html#cbca0b6", null ],
    [ "getEmailDomains", "Helix_Asana_Workspace.html#21e8117", null ],
    [ "getName", "Helix_Asana_Workspace.html#8a0b8ec", null ],
    [ "getPortfolios", "Helix_Asana_Workspace.html#2ffe879", null ],
    [ "getProjects", "Helix_Asana_Workspace.html#abcd827", null ],
    [ "getTags", "Helix_Asana_Workspace.html#bfd56af", null ],
    [ "getTeams", "Helix_Asana_Workspace.html#1fc9b8a", null ],
    [ "getUserByEmail", "Helix_Asana_Workspace.html#83ef253", null ],
    [ "getUsers", "Helix_Asana_Workspace.html#3b2eb4d", null ],
    [ "getWebhooks", "Helix_Asana_Workspace.html#ecb178d", null ],
    [ "isOrganization", "Helix_Asana_Workspace.html#1132cda", null ],
    [ "newCustomField", "Helix_Asana_Workspace.html#7850e28", null ],
    [ "newPortfolio", "Helix_Asana_Workspace.html#1bf5ad9", null ],
    [ "newProject", "Helix_Asana_Workspace.html#534ab63", null ],
    [ "newTag", "Helix_Asana_Workspace.html#40a4f85", null ],
    [ "newTask", "Helix_Asana_Workspace.html#8a4ac2f", null ],
    [ "selectCustomFields", "Helix_Asana_Workspace.html#54088de", null ],
    [ "selectPortfolios", "Helix_Asana_Workspace.html#d2df1ec", null ],
    [ "selectProjects", "Helix_Asana_Workspace.html#4de31b3", null ],
    [ "selectTags", "Helix_Asana_Workspace.html#4af07e5", null ],
    [ "selectTeams", "Helix_Asana_Workspace.html#b8f5481", null ],
    [ "selectUsers", "Helix_Asana_Workspace.html#c8867dc", null ],
    [ "setName", "Helix_Asana_Workspace.html#2f41205", null ]
];