var Helix_Asana_Base_Data =
[
    [ "$api", "Helix_Asana_Base_Data.html#79670fb", null ],
    [ "$data", "Helix_Asana_Base_Data.html#949c8d3", null ],
    [ "$diff", "Helix_Asana_Base_Data.html#cc7f43e", null ],
    [ "MAP", "Helix_Asana_Base_Data.html#9c07f6e", null ],
    [ "__construct", "Helix_Asana_Base_Data.html#ce939ba", null ],
    [ "__call", "Helix_Asana_Base_Data.html#1dca3f4", null ],
    [ "__serialize", "Helix_Asana_Base_Data.html#8770cd0", null ],
    [ "__unserialize", "Helix_Asana_Base_Data.html#698e15d", null ],
    [ "_get", "Helix_Asana_Base_Data.html#d5105e5", null ],
    [ "_has", "Helix_Asana_Base_Data.html#a688696", null ],
    [ "_hydrate", "Helix_Asana_Base_Data.html#5ecb440", null ],
    [ "_is", "Helix_Asana_Base_Data.html#0d08a84", null ],
    [ "_of", "Helix_Asana_Base_Data.html#c2bed3a", null ],
    [ "_select", "Helix_Asana_Base_Data.html#fa70ca1", null ],
    [ "_set", "Helix_Asana_Base_Data.html#1eab51a", null ],
    [ "_setData", "Helix_Asana_Base_Data.html#e470999", null ],
    [ "_setField", "Helix_Asana_Base_Data.html#ab60c3b", null ],
    [ "isDiff", "Helix_Asana_Base_Data.html#c435fd7", null ],
    [ "jsonSerialize", "Helix_Asana_Base_Data.html#a630cbe", null ],
    [ "offsetExists", "Helix_Asana_Base_Data.html#a6e5636", null ],
    [ "offsetGet", "Helix_Asana_Base_Data.html#8b8df41", null ],
    [ "offsetSet", "Helix_Asana_Base_Data.html#e8b5dcd", null ],
    [ "offsetUnset", "Helix_Asana_Base_Data.html#4fc83cb", null ],
    [ "toArray", "Helix_Asana_Base_Data.html#7258986", null ]
];