var Helix_Socket_WebSocket_FrameHandler =
[
    [ "$buffer", "Helix_Socket_WebSocket_FrameHandler.html#b3fca54", null ],
    [ "$client", "Helix_Socket_WebSocket_FrameHandler.html#ccf486f", null ],
    [ "$continue", "Helix_Socket_WebSocket_FrameHandler.html#2084c46", null ],
    [ "$fragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#90e169a", null ],
    [ "$maxLength", "Helix_Socket_WebSocket_FrameHandler.html#ae0333e", null ],
    [ "$reader", "Helix_Socket_WebSocket_FrameHandler.html#16ccb13", null ],
    [ "$stream", "Helix_Socket_WebSocket_FrameHandler.html#4caf6f9", null ],
    [ "__construct", "Helix_Socket_WebSocket_FrameHandler.html#647bec6", null ],
    [ "getFragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#075e22b", null ],
    [ "getMaxLength", "Helix_Socket_WebSocket_FrameHandler.html#ad9ff6a", null ],
    [ "isStream", "Helix_Socket_WebSocket_FrameHandler.html#337eae2", null ],
    [ "onBinary", "Helix_Socket_WebSocket_FrameHandler.html#e2959ce", null ],
    [ "onClose", "Helix_Socket_WebSocket_FrameHandler.html#4943b48", null ],
    [ "onContinuation", "Helix_Socket_WebSocket_FrameHandler.html#807777d", null ],
    [ "onControl", "Helix_Socket_WebSocket_FrameHandler.html#eff865e", null ],
    [ "onData", "Helix_Socket_WebSocket_FrameHandler.html#cd130c9", null ],
    [ "onData_CheckLength", "Helix_Socket_WebSocket_FrameHandler.html#b4513d9", null ],
    [ "onFrame", "Helix_Socket_WebSocket_FrameHandler.html#17db452", null ],
    [ "onPing", "Helix_Socket_WebSocket_FrameHandler.html#b663be6", null ],
    [ "onPong", "Helix_Socket_WebSocket_FrameHandler.html#4cf62fa", null ],
    [ "onReadable", "Helix_Socket_WebSocket_FrameHandler.html#d188c8a", null ],
    [ "onText", "Helix_Socket_WebSocket_FrameHandler.html#3c8edf8", null ],
    [ "setFragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#6c30e36", null ],
    [ "setMaxLength", "Helix_Socket_WebSocket_FrameHandler.html#38a72a3", null ],
    [ "setStream", "Helix_Socket_WebSocket_FrameHandler.html#db46e0f", null ],
    [ "write", "Helix_Socket_WebSocket_FrameHandler.html#179ab33", null ],
    [ "writeBinary", "Helix_Socket_WebSocket_FrameHandler.html#aaf4461", null ],
    [ "writeClose", "Helix_Socket_WebSocket_FrameHandler.html#12e42e7", null ],
    [ "writeFrame", "Helix_Socket_WebSocket_FrameHandler.html#a192818", null ],
    [ "writePing", "Helix_Socket_WebSocket_FrameHandler.html#538847a", null ],
    [ "writePong", "Helix_Socket_WebSocket_FrameHandler.html#f678695", null ],
    [ "writeText", "Helix_Socket_WebSocket_FrameHandler.html#3145d99", null ]
];