var Helix_Socket_WebSocket_WebSocketClient =
[
    [ "$frameHandler", "Helix_Socket_WebSocket_WebSocketClient.html#8bdc18d", null ],
    [ "$handshake", "Helix_Socket_WebSocket_WebSocketClient.html#ae57806", null ],
    [ "$server", "Helix_Socket_WebSocket_WebSocketClient.html#34c166a", null ],
    [ "$state", "Helix_Socket_WebSocket_WebSocketClient.html#18513f5", null ],
    [ "STATE_CLOSED", "Helix_Socket_WebSocket_WebSocketClient.html#9cc1065", null ],
    [ "STATE_HANDSHAKE", "Helix_Socket_WebSocket_WebSocketClient.html#ae1d8cb", null ],
    [ "STATE_OK", "Helix_Socket_WebSocket_WebSocketClient.html#a3d2f0b", null ],
    [ "__construct", "Helix_Socket_WebSocket_WebSocketClient.html#1b5f994", null ],
    [ "close", "Helix_Socket_WebSocket_WebSocketClient.html#a5cb293", null ],
    [ "getFrameHandler", "Helix_Socket_WebSocket_WebSocketClient.html#1235bf8", null ],
    [ "getServer", "Helix_Socket_WebSocket_WebSocketClient.html#999557f", null ],
    [ "getState", "Helix_Socket_WebSocket_WebSocketClient.html#2eff5d8", null ],
    [ "isNegotiating", "Helix_Socket_WebSocket_WebSocketClient.html#0d27afc", null ],
    [ "isOk", "Helix_Socket_WebSocket_WebSocketClient.html#47070fd", null ],
    [ "onBinary", "Helix_Socket_WebSocket_WebSocketClient.html#30d1d8c", null ],
    [ "onClose", "Helix_Socket_WebSocket_WebSocketClient.html#98d0499", null ],
    [ "onOutOfBand", "Helix_Socket_WebSocket_WebSocketClient.html#ec44db7", null ],
    [ "onPing", "Helix_Socket_WebSocket_WebSocketClient.html#9f8d8da", null ],
    [ "onPong", "Helix_Socket_WebSocket_WebSocketClient.html#c9257f9", null ],
    [ "onReadable", "Helix_Socket_WebSocket_WebSocketClient.html#d188c8a", null ],
    [ "onStateOk", "Helix_Socket_WebSocket_WebSocketClient.html#311725e", null ],
    [ "onText", "Helix_Socket_WebSocket_WebSocketClient.html#852e93e", null ],
    [ "writeBinary", "Helix_Socket_WebSocket_WebSocketClient.html#28d6bb4", null ],
    [ "writeJSON", "Helix_Socket_WebSocket_WebSocketClient.html#ba8bc09", null ],
    [ "writeText", "Helix_Socket_WebSocket_WebSocketClient.html#6874e08", null ]
];