var Helix_Socket_WebSocket_FrameHandler =
[
    [ "$buffer", "Helix_Socket_WebSocket_FrameHandler.html#b3fca54", null ],
    [ "$client", "Helix_Socket_WebSocket_FrameHandler.html#ccf486f", null ],
    [ "$continue", "Helix_Socket_WebSocket_FrameHandler.html#2084c46", null ],
    [ "$fragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#90e169a", null ],
    [ "$maxLength", "Helix_Socket_WebSocket_FrameHandler.html#ae0333e", null ],
    [ "__construct", "Helix_Socket_WebSocket_FrameHandler.html#647bec6", null ],
    [ "getFragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#075e22b", null ],
    [ "getMaxLength", "Helix_Socket_WebSocket_FrameHandler.html#ad9ff6a", null ],
    [ "onBinary", "Helix_Socket_WebSocket_FrameHandler.html#5e509af", null ],
    [ "onClose", "Helix_Socket_WebSocket_FrameHandler.html#a2b6ecf", null ],
    [ "onContinue", "Helix_Socket_WebSocket_FrameHandler.html#89af4f5", null ],
    [ "onControl", "Helix_Socket_WebSocket_FrameHandler.html#32844f7", null ],
    [ "onData", "Helix_Socket_WebSocket_FrameHandler.html#26bfd76", null ],
    [ "onData_SetContinue", "Helix_Socket_WebSocket_FrameHandler.html#a589062", null ],
    [ "onFrame", "Helix_Socket_WebSocket_FrameHandler.html#17db452", null ],
    [ "onFrame_CheckLength", "Helix_Socket_WebSocket_FrameHandler.html#433fdea", null ],
    [ "onFrame_CheckRsv", "Helix_Socket_WebSocket_FrameHandler.html#5cec472", null ],
    [ "onPing", "Helix_Socket_WebSocket_FrameHandler.html#5b8193a", null ],
    [ "onPong", "Helix_Socket_WebSocket_FrameHandler.html#39131f5", null ],
    [ "onText", "Helix_Socket_WebSocket_FrameHandler.html#c34631d", null ],
    [ "setFragmentSize", "Helix_Socket_WebSocket_FrameHandler.html#6c30e36", null ],
    [ "setMaxLength", "Helix_Socket_WebSocket_FrameHandler.html#38a72a3", null ],
    [ "write", "Helix_Socket_WebSocket_FrameHandler.html#179ab33", null ],
    [ "writeBinary", "Helix_Socket_WebSocket_FrameHandler.html#aaf4461", null ],
    [ "writeClose", "Helix_Socket_WebSocket_FrameHandler.html#12e42e7", null ],
    [ "writeFrame", "Helix_Socket_WebSocket_FrameHandler.html#a192818", null ],
    [ "writePing", "Helix_Socket_WebSocket_FrameHandler.html#538847a", null ],
    [ "writePong", "Helix_Socket_WebSocket_FrameHandler.html#f678695", null ],
    [ "writeText", "Helix_Socket_WebSocket_FrameHandler.html#3145d99", null ]
];