var Helix_Shopify_Collection_AbstractCollection =
[
    [ "MAP", "Helix_Shopify_Collection_AbstractCollection.html#9c07f6e", null ],
    [ "SCOPE_GLOBAL", "Helix_Shopify_Collection_AbstractCollection.html#b5ead7e", null ],
    [ "SCOPE_WEB", "Helix_Shopify_Collection_AbstractCollection.html#a051e0d", null ],
    [ "SORT_ALPHA_ASC", "Helix_Shopify_Collection_AbstractCollection.html#4e79b9b", null ],
    [ "SORT_ALPHA_DESC", "Helix_Shopify_Collection_AbstractCollection.html#d0ff77f", null ],
    [ "SORT_BEST_SELLING", "Helix_Shopify_Collection_AbstractCollection.html#4f06acc", null ],
    [ "SORT_CREATED", "Helix_Shopify_Collection_AbstractCollection.html#9e3c356", null ],
    [ "SORT_CREATED_DESC", "Helix_Shopify_Collection_AbstractCollection.html#ed5e18c", null ],
    [ "SORT_MANUAL", "Helix_Shopify_Collection_AbstractCollection.html#5677ab6", null ],
    [ "SORT_PRICE_ASC", "Helix_Shopify_Collection_AbstractCollection.html#8fe10fc", null ],
    [ "SORT_PRICE_DESC", "Helix_Shopify_Collection_AbstractCollection.html#ce125e7", null ],
    [ "getBodyHtml", "Helix_Shopify_Collection_AbstractCollection.html#25f6887", null ],
    [ "getHandle", "Helix_Shopify_Collection_AbstractCollection.html#b21fe3f", null ],
    [ "getImage", "Helix_Shopify_Collection_AbstractCollection.html#b536221", null ],
    [ "getProducts", "Helix_Shopify_Collection_AbstractCollection.html#26b99cf", null ],
    [ "getPublishedAt", "Helix_Shopify_Collection_AbstractCollection.html#2345b78", null ],
    [ "getPublishedScope", "Helix_Shopify_Collection_AbstractCollection.html#38f8b03", null ],
    [ "getSortOrder", "Helix_Shopify_Collection_AbstractCollection.html#7768c7d", null ],
    [ "getTemplateSuffix", "Helix_Shopify_Collection_AbstractCollection.html#a64bc00", null ],
    [ "getTitle", "Helix_Shopify_Collection_AbstractCollection.html#9660eac", null ],
    [ "getUpdatedAt", "Helix_Shopify_Collection_AbstractCollection.html#975c7c7", null ],
    [ "newCollect", "Helix_Shopify_Collection_AbstractCollection.html#1002820", null ],
    [ "setBodyHtml", "Helix_Shopify_Collection_AbstractCollection.html#69659e6", null ],
    [ "setHandle", "Helix_Shopify_Collection_AbstractCollection.html#3b1f5b1", null ],
    [ "setImage", "Helix_Shopify_Collection_AbstractCollection.html#c93a672", null ],
    [ "setSortOrder", "Helix_Shopify_Collection_AbstractCollection.html#0c79c60", null ],
    [ "setTemplateSuffix", "Helix_Shopify_Collection_AbstractCollection.html#88a035d", null ],
    [ "setTitle", "Helix_Shopify_Collection_AbstractCollection.html#b65055b", null ]
];