var Helix_Shopify_Order_AbstractOrder =
[
    [ "MAP", "Helix_Shopify_Order_AbstractOrder.html#9c07f6e", null ],
    [ "getBillingAddress", "Helix_Shopify_Order_AbstractOrder.html#edff07a", null ],
    [ "getCreatedAt", "Helix_Shopify_Order_AbstractOrder.html#1adffdc", null ],
    [ "getCurrency", "Helix_Shopify_Order_AbstractOrder.html#60031d8", null ],
    [ "getCustomer", "Helix_Shopify_Order_AbstractOrder.html#b808d6c", null ],
    [ "getEmail", "Helix_Shopify_Order_AbstractOrder.html#30d49cf", null ],
    [ "getLineItems", "Helix_Shopify_Order_AbstractOrder.html#6778c13", null ],
    [ "getName", "Helix_Shopify_Order_AbstractOrder.html#8a0b8ec", null ],
    [ "getNote", "Helix_Shopify_Order_AbstractOrder.html#ba7d11a", null ],
    [ "getNoteAttributes", "Helix_Shopify_Order_AbstractOrder.html#7cc9713", null ],
    [ "getShippingAddress", "Helix_Shopify_Order_AbstractOrder.html#01806dd", null ],
    [ "getSubtotalPrice", "Helix_Shopify_Order_AbstractOrder.html#c7f4d2f", null ],
    [ "getTags", "Helix_Shopify_Order_AbstractOrder.html#78fd296", null ],
    [ "getTaxLines", "Helix_Shopify_Order_AbstractOrder.html#eabca2a", null ],
    [ "getTotalPrice", "Helix_Shopify_Order_AbstractOrder.html#ff57835", null ],
    [ "getTotalTax", "Helix_Shopify_Order_AbstractOrder.html#fbec714", null ],
    [ "getUpdatedAt", "Helix_Shopify_Order_AbstractOrder.html#975c7c7", null ],
    [ "hasTaxesIncluded", "Helix_Shopify_Order_AbstractOrder.html#a3b5a6d", null ],
    [ "setBillingAddress", "Helix_Shopify_Order_AbstractOrder.html#21ad303", null ],
    [ "setCurrency", "Helix_Shopify_Order_AbstractOrder.html#69853ad", null ],
    [ "setCustomer", "Helix_Shopify_Order_AbstractOrder.html#f363492", null ],
    [ "setEmail", "Helix_Shopify_Order_AbstractOrder.html#996536f", null ],
    [ "setName", "Helix_Shopify_Order_AbstractOrder.html#2f41205", null ],
    [ "setNote", "Helix_Shopify_Order_AbstractOrder.html#3c868f4", null ],
    [ "setNoteAttributes", "Helix_Shopify_Order_AbstractOrder.html#c56a1f4", null ],
    [ "setShippingAddress", "Helix_Shopify_Order_AbstractOrder.html#5969b22", null ],
    [ "setSubtotalPrice", "Helix_Shopify_Order_AbstractOrder.html#782adaa", null ],
    [ "setTags", "Helix_Shopify_Order_AbstractOrder.html#02ae122", null ],
    [ "setTaxesIncluded", "Helix_Shopify_Order_AbstractOrder.html#a3c59e7", null ],
    [ "setTaxLines", "Helix_Shopify_Order_AbstractOrder.html#a41b11f", null ],
    [ "setTotalPrice", "Helix_Shopify_Order_AbstractOrder.html#30086a3", null ],
    [ "setTotalTax", "Helix_Shopify_Order_AbstractOrder.html#244ee79", null ]
];