var Helix_Shopify_DraftOrder =
[
    [ "DIR", "Helix_Shopify_DraftOrder.html#c482d92", null ],
    [ "MAP", "Helix_Shopify_DraftOrder.html#9c07f6e", null ],
    [ "SEARCH_STATUS_COMPLETE", "Helix_Shopify_DraftOrder.html#6e2d074", null ],
    [ "SEARCH_STATUS_INVOICED", "Helix_Shopify_DraftOrder.html#f57e736", null ],
    [ "SEARCH_STATUS_OPEN", "Helix_Shopify_DraftOrder.html#0c935dc", null ],
    [ "STATUS_COMPLETE", "Helix_Shopify_DraftOrder.html#c8ab184", null ],
    [ "STATUS_INVOICED", "Helix_Shopify_DraftOrder.html#2fcebe8", null ],
    [ "STATUS_OPEN", "Helix_Shopify_DraftOrder.html#f6189b9", null ],
    [ "TYPE", "Helix_Shopify_DraftOrder.html#0cb7892", null ],
    [ "complete", "Helix_Shopify_DraftOrder.html#ae14c7a", null ],
    [ "getAppliedDiscount", "Helix_Shopify_DraftOrder.html#ea31f95", null ],
    [ "getCompletedAt", "Helix_Shopify_DraftOrder.html#c5a9eee", null ],
    [ "getCustomerId", "Helix_Shopify_DraftOrder.html#65bbf7b", null ],
    [ "getInvoiceSentAt", "Helix_Shopify_DraftOrder.html#479cce7", null ],
    [ "getInvoiceUrl", "Helix_Shopify_DraftOrder.html#8468a5b", null ],
    [ "getOrderId", "Helix_Shopify_DraftOrder.html#b3441e5", null ],
    [ "getShippingLine", "Helix_Shopify_DraftOrder.html#73032d7", null ],
    [ "getStatus", "Helix_Shopify_DraftOrder.html#575cf10", null ],
    [ "isTaxExempt", "Helix_Shopify_DraftOrder.html#4d642e5", null ],
    [ "sendInvoice", "Helix_Shopify_DraftOrder.html#4e1bb68", null ],
    [ "setInvoiceSentAt", "Helix_Shopify_DraftOrder.html#f0c5c4f", null ],
    [ "setLineItems", "Helix_Shopify_DraftOrder.html#ec0827f", null ],
    [ "setShippingLine", "Helix_Shopify_DraftOrder.html#1634328", null ],
    [ "setTaxExempt", "Helix_Shopify_DraftOrder.html#b6249ed", null ],
    [ "setUseCustomerDefaultAddress", "Helix_Shopify_DraftOrder.html#2cdaa3c", null ]
];