var Helix_Shopify_Customer_Address =
[
    [ "DIR", "Helix_Shopify_Customer_Address.html#c482d92", null ],
    [ "TYPE", "Helix_Shopify_Customer_Address.html#0cb7892", null ],
    [ "_container", "Helix_Shopify_Customer_Address.html#9f43825", null ],
    [ "_onDelete", "Helix_Shopify_Customer_Address.html#bf950d4", null ],
    [ "_onSave", "Helix_Shopify_Customer_Address.html#bbc691a", null ],
    [ "getAddress1", "Helix_Shopify_Customer_Address.html#2223adf", null ],
    [ "getAddress2", "Helix_Shopify_Customer_Address.html#b7d438d", null ],
    [ "getCity", "Helix_Shopify_Customer_Address.html#1f53525", null ],
    [ "getCompany", "Helix_Shopify_Customer_Address.html#fb95a2a", null ],
    [ "getCountry", "Helix_Shopify_Customer_Address.html#76fdf76", null ],
    [ "getCountryCode", "Helix_Shopify_Customer_Address.html#aab7d50", null ],
    [ "getCountryName", "Helix_Shopify_Customer_Address.html#b93c8df", null ],
    [ "getCustomer", "Helix_Shopify_Customer_Address.html#52012d4", null ],
    [ "getCustomerId", "Helix_Shopify_Customer_Address.html#65bbf7b", null ],
    [ "getName", "Helix_Shopify_Customer_Address.html#8a0b8ec", null ],
    [ "getPhone", "Helix_Shopify_Customer_Address.html#4f215a4", null ],
    [ "getProvince", "Helix_Shopify_Customer_Address.html#8ee23e5", null ],
    [ "getProvinceCode", "Helix_Shopify_Customer_Address.html#468c7a5", null ],
    [ "getState", "Helix_Shopify_Customer_Address.html#ed4c0cd", null ],
    [ "getStateCode", "Helix_Shopify_Customer_Address.html#53f4437", null ],
    [ "getZip", "Helix_Shopify_Customer_Address.html#793213f", null ],
    [ "hasPhone", "Helix_Shopify_Customer_Address.html#79c5101", null ],
    [ "isDefault", "Helix_Shopify_Customer_Address.html#241616c", null ],
    [ "setAddress1", "Helix_Shopify_Customer_Address.html#7d2b0a2", null ],
    [ "setAddress2", "Helix_Shopify_Customer_Address.html#a45e64b", null ],
    [ "setCity", "Helix_Shopify_Customer_Address.html#03ce819", null ],
    [ "setCompany", "Helix_Shopify_Customer_Address.html#6ec5aef", null ],
    [ "setCountry", "Helix_Shopify_Customer_Address.html#dda40f3", null ],
    [ "setCountryName", "Helix_Shopify_Customer_Address.html#e472e16", null ],
    [ "setDefault", "Helix_Shopify_Customer_Address.html#02940e0", null ],
    [ "setName", "Helix_Shopify_Customer_Address.html#2f41205", null ],
    [ "setPhone", "Helix_Shopify_Customer_Address.html#bc5b3e7", null ],
    [ "setProvince", "Helix_Shopify_Customer_Address.html#a4f40f0", null ],
    [ "setState", "Helix_Shopify_Customer_Address.html#ea2bfc8", null ],
    [ "setZip", "Helix_Shopify_Customer_Address.html#2492b63", null ]
];