var Helix_Shopify_Metafield =
[
    [ "$container", "Helix_Shopify_Metafield.html#0daadeb", null ],
    [ "DIR", "Helix_Shopify_Metafield.html#c482d92", null ],
    [ "TYPE", "Helix_Shopify_Metafield.html#0cb7892", null ],
    [ "TYPE_INT", "Helix_Shopify_Metafield.html#7c7885d", null ],
    [ "TYPE_JSON", "Helix_Shopify_Metafield.html#256c932", null ],
    [ "TYPE_STRING", "Helix_Shopify_Metafield.html#d484b4e", null ],
    [ "__construct", "Helix_Shopify_Metafield.html#39d5cd0", null ],
    [ "__toString", "Helix_Shopify_Metafield.html#f5ddf7f", null ],
    [ "_container", "Helix_Shopify_Metafield.html#9f43825", null ],
    [ "_dir", "Helix_Shopify_Metafield.html#249b4fd", null ],
    [ "getCreatedAt", "Helix_Shopify_Metafield.html#1adffdc", null ],
    [ "getDescription", "Helix_Shopify_Metafield.html#cf1cf5f", null ],
    [ "getKey", "Helix_Shopify_Metafield.html#a963ee5", null ],
    [ "getNamespace", "Helix_Shopify_Metafield.html#5761fd9", null ],
    [ "getOwnerId", "Helix_Shopify_Metafield.html#fb2e6cb", null ],
    [ "getOwnerResource", "Helix_Shopify_Metafield.html#665368e", null ],
    [ "getResource", "Helix_Shopify_Metafield.html#f9d4a42", null ],
    [ "getUpdatedAt", "Helix_Shopify_Metafield.html#975c7c7", null ],
    [ "getValue", "Helix_Shopify_Metafield.html#c01e1c7", null ],
    [ "getValueType", "Helix_Shopify_Metafield.html#b3026c9", null ],
    [ "isInt", "Helix_Shopify_Metafield.html#c3ad41e", null ],
    [ "isJson", "Helix_Shopify_Metafield.html#124e82a", null ],
    [ "isString", "Helix_Shopify_Metafield.html#0ae6cbc", null ],
    [ "setDescription", "Helix_Shopify_Metafield.html#cde74aa", null ],
    [ "setKey", "Helix_Shopify_Metafield.html#f912478", null ],
    [ "setNamespace", "Helix_Shopify_Metafield.html#de4fffc", null ],
    [ "setValue", "Helix_Shopify_Metafield.html#37f3831", null ]
];