var Helix_Shopify_Blog_Article =
[
    [ "DIR", "Helix_Shopify_Blog_Article.html#c482d92", null ],
    [ "MAP", "Helix_Shopify_Blog_Article.html#9c07f6e", null ],
    [ "TYPE", "Helix_Shopify_Blog_Article.html#0cb7892", null ],
    [ "_container", "Helix_Shopify_Blog_Article.html#9f43825", null ],
    [ "getAuthor", "Helix_Shopify_Blog_Article.html#f736f45", null ],
    [ "getBlog", "Helix_Shopify_Blog_Article.html#f7f0e46", null ],
    [ "getBlogId", "Helix_Shopify_Blog_Article.html#b934524", null ],
    [ "getBodyHtml", "Helix_Shopify_Blog_Article.html#25f6887", null ],
    [ "getComments", "Helix_Shopify_Blog_Article.html#00709ba", null ],
    [ "getCommentsCount", "Helix_Shopify_Blog_Article.html#694e22c", null ],
    [ "getCreatedAt", "Helix_Shopify_Blog_Article.html#1adffdc", null ],
    [ "getHandle", "Helix_Shopify_Blog_Article.html#b21fe3f", null ],
    [ "getImage", "Helix_Shopify_Blog_Article.html#b536221", null ],
    [ "getPublished", "Helix_Shopify_Blog_Article.html#85f53e3", null ],
    [ "getPublishedAt", "Helix_Shopify_Blog_Article.html#04e755a", null ],
    [ "getSummaryHtml", "Helix_Shopify_Blog_Article.html#b60cd76", null ],
    [ "getTags", "Helix_Shopify_Blog_Article.html#78fd296", null ],
    [ "getTemplateSuffix", "Helix_Shopify_Blog_Article.html#1b7107c", null ],
    [ "getTitle", "Helix_Shopify_Blog_Article.html#9660eac", null ],
    [ "getUpdatedAt", "Helix_Shopify_Blog_Article.html#975c7c7", null ],
    [ "getUserId", "Helix_Shopify_Blog_Article.html#9845aeb", null ],
    [ "newComment", "Helix_Shopify_Blog_Article.html#682f071", null ],
    [ "selectComments", "Helix_Shopify_Blog_Article.html#406d1af", null ],
    [ "setAuthor", "Helix_Shopify_Blog_Article.html#58f8cc7", null ],
    [ "setBodyHtml", "Helix_Shopify_Blog_Article.html#69659e6", null ],
    [ "setHandle", "Helix_Shopify_Blog_Article.html#3b1f5b1", null ],
    [ "setImage", "Helix_Shopify_Blog_Article.html#c93a672", null ],
    [ "setPublished", "Helix_Shopify_Blog_Article.html#04d8d51", null ],
    [ "setPublishedAt", "Helix_Shopify_Blog_Article.html#a84a370", null ],
    [ "setSummaryHtml", "Helix_Shopify_Blog_Article.html#88c5784", null ],
    [ "setTags", "Helix_Shopify_Blog_Article.html#95ee752", null ],
    [ "setTemplateSuffix", "Helix_Shopify_Blog_Article.html#476b4a9", null ],
    [ "setTitle", "Helix_Shopify_Blog_Article.html#b65055b", null ]
];