var Helix_Shopify_Order_Refund =
[
    [ "$order", "Helix_Shopify_Order_Refund.html#63c2f13", null ],
    [ "DIR", "Helix_Shopify_Order_Refund.html#c482d92", null ],
    [ "MAP", "Helix_Shopify_Order_Refund.html#9c07f6e", null ],
    [ "REASON_CUSTOMER", "Helix_Shopify_Order_Refund.html#83299ab", null ],
    [ "REASON_DAMAGE", "Helix_Shopify_Order_Refund.html#77cd787", null ],
    [ "REASON_OTHER", "Helix_Shopify_Order_Refund.html#a64c08b", null ],
    [ "REASON_RESTOCK", "Helix_Shopify_Order_Refund.html#89c4134", null ],
    [ "TYPE", "Helix_Shopify_Order_Refund.html#0cb7892", null ],
    [ "__construct", "Helix_Shopify_Order_Refund.html#0f9cf53", null ],
    [ "_container", "Helix_Shopify_Order_Refund.html#9f43825", null ],
    [ "getCreatedAt", "Helix_Shopify_Order_Refund.html#1adffdc", null ],
    [ "getId", "Helix_Shopify_Order_Refund.html#75b4d5c", null ],
    [ "getNote", "Helix_Shopify_Order_Refund.html#ba7d11a", null ],
    [ "getOrder", "Helix_Shopify_Order_Refund.html#b19ad72", null ],
    [ "getOrderAdjustments", "Helix_Shopify_Order_Refund.html#efc59a5", null ],
    [ "getProcessedAt", "Helix_Shopify_Order_Refund.html#1270417", null ],
    [ "getRefundLineItems", "Helix_Shopify_Order_Refund.html#2cd04e9", null ],
    [ "getTransactions", "Helix_Shopify_Order_Refund.html#012e4c2", null ],
    [ "getUserId", "Helix_Shopify_Order_Refund.html#9845aeb", null ],
    [ "hasOrderAdjustments", "Helix_Shopify_Order_Refund.html#ae4a3f0", null ],
    [ "hasRefundLineItems", "Helix_Shopify_Order_Refund.html#2a10ddb", null ],
    [ "hasTransactions", "Helix_Shopify_Order_Refund.html#81f28b6", null ],
    [ "newItem", "Helix_Shopify_Order_Refund.html#b7d33de", null ],
    [ "newTransaction", "Helix_Shopify_Order_Refund.html#2907cbe", null ],
    [ "setCurrency", "Helix_Shopify_Order_Refund.html#1378d7f", null ],
    [ "setDiscrepancyReason", "Helix_Shopify_Order_Refund.html#95b1aca", null ],
    [ "setFullShipping", "Helix_Shopify_Order_Refund.html#6119006", null ],
    [ "setNote", "Helix_Shopify_Order_Refund.html#3c868f4", null ],
    [ "setNotify", "Helix_Shopify_Order_Refund.html#3c46e57", null ],
    [ "setProcessedAt", "Helix_Shopify_Order_Refund.html#32f80f9", null ],
    [ "setRefundLineItems", "Helix_Shopify_Order_Refund.html#a3dd32b", null ],
    [ "setShippingAmount", "Helix_Shopify_Order_Refund.html#aa8afd2", null ],
    [ "setTransactions", "Helix_Shopify_Order_Refund.html#ccbf4bc", null ],
    [ "setUserId", "Helix_Shopify_Order_Refund.html#6c2ebee", null ]
];