var Helix_Shopify_Api =
[
    [ "$domain", "Helix_Shopify_Api.html#8286e4a", null ],
    [ "$key", "Helix_Shopify_Api.html#a7b6490", null ],
    [ "$logger", "Helix_Shopify_Api.html#13c9546", null ],
    [ "$password", "Helix_Shopify_Api.html#ea0703d", null ],
    [ "$pool", "Helix_Shopify_Api.html#bcc3bdc", null ],
    [ "__construct", "Helix_Shopify_Api.html#f35d4be", null ],
    [ "advancedSearch", "Helix_Shopify_Api.html#f88e84c", null ],
    [ "delete", "Helix_Shopify_Api.html#025b5d7", null ],
    [ "exec", "Helix_Shopify_Api.html#5397849", null ],
    [ "factory", "Helix_Shopify_Api.html#b5017c2", null ],
    [ "factoryAll", "Helix_Shopify_Api.html#94d9125", null ],
    [ "get", "Helix_Shopify_Api.html#1dac3a4", null ],
    [ "getLocation", "Helix_Shopify_Api.html#2a63990", null ],
    [ "getLogger", "Helix_Shopify_Api.html#f3718e8", null ],
    [ "getMe", "Helix_Shopify_Api.html#47d6417", null ],
    [ "getPool", "Helix_Shopify_Api.html#218dcbf", null ],
    [ "getShop", "Helix_Shopify_Api.html#6baad2a", null ],
    [ "load", "Helix_Shopify_Api.html#0918e17", null ],
    [ "loadAll", "Helix_Shopify_Api.html#dc17fef", null ],
    [ "post", "Helix_Shopify_Api.html#011429c", null ],
    [ "put", "Helix_Shopify_Api.html#61430aa", null ],
    [ "setLogger", "Helix_Shopify_Api.html#daa64f6", null ]
];