var Helix_Shopify_User =
[
    [ "PERM_APPLICATIONS", "Helix_Shopify_User.html#4ab4786", null ],
    [ "PERM_CUSTOMERS", "Helix_Shopify_User.html#10b22c0", null ],
    [ "PERM_DASHBOARD", "Helix_Shopify_User.html#75f0d3f", null ],
    [ "PERM_FULL", "Helix_Shopify_User.html#f50496c", null ],
    [ "PERM_GIFT_CARDS", "Helix_Shopify_User.html#2a7439f", null ],
    [ "PERM_LINKS", "Helix_Shopify_User.html#1a8bc1d", null ],
    [ "PERM_MARKETING", "Helix_Shopify_User.html#c058656", null ],
    [ "PERM_ORDERS", "Helix_Shopify_User.html#822d4a1", null ],
    [ "PERM_PAGES", "Helix_Shopify_User.html#61636ae", null ],
    [ "PERM_PREFERENCES", "Helix_Shopify_User.html#53cb086", null ],
    [ "PERM_PRODUCTS", "Helix_Shopify_User.html#3efd4ff", null ],
    [ "PERM_REPORTS", "Helix_Shopify_User.html#0c15cc6", null ],
    [ "PERM_THEMES", "Helix_Shopify_User.html#859328d", null ],
    [ "TYPE_COLLABORATOR", "Helix_Shopify_User.html#41eb88b", null ],
    [ "TYPE_INVITED", "Helix_Shopify_User.html#01fc19c", null ],
    [ "TYPE_REGULAR", "Helix_Shopify_User.html#13422ab", null ],
    [ "TYPE_RESTRICTED", "Helix_Shopify_User.html#6b34297", null ],
    [ "getBio", "Helix_Shopify_User.html#8e1e1d0", null ],
    [ "getEmail", "Helix_Shopify_User.html#30d49cf", null ],
    [ "getFirstName", "Helix_Shopify_User.html#08f1743", null ],
    [ "getIm", "Helix_Shopify_User.html#41cba1a", null ],
    [ "getLastName", "Helix_Shopify_User.html#e7a33e9", null ],
    [ "getLocale", "Helix_Shopify_User.html#336c8bd", null ],
    [ "getPermissions", "Helix_Shopify_User.html#36e3737", null ],
    [ "getPhone", "Helix_Shopify_User.html#4f215a4", null ],
    [ "getReceiveAnnouncements", "Helix_Shopify_User.html#22b3e9a", null ],
    [ "getUrl", "Helix_Shopify_User.html#40cc775", null ],
    [ "getUserType", "Helix_Shopify_User.html#289206a", null ],
    [ "hasPermissions", "Helix_Shopify_User.html#64f775d", null ],
    [ "isAccountOwner", "Helix_Shopify_User.html#760d1e3", null ]
];